module.exports = {
  default: {},
  applicationName: 'Spay',
  applicationId: 'com.spay',
  nativeApplicationVersion: '1.0.0',
  nativeBuildVersion: '1',
  manifest: {},
  expoConfig: {},
  cacheDirectory: 'file:///cache',
  documentDirectory: 'file:///docs',
  getContentUriAsync: () => Promise.resolve('content://uri'),
  startActivityAsync: () => Promise.resolve(),
  reloadAsync: () => Promise.resolve(),
  checkForUpdateAsync: () => Promise.resolve({ isAvailable: false }),
  fetchUpdateAsync: () => Promise.resolve(),
  exitApp: () => {},
  getItem: () => null,
  setItem: () => {},
  deleteItemAsync: () => Promise.resolve(),
  Image: 'Image',
  hasHardwareAsync: () => Promise.resolve(false),
  isEnrolledAsync: () => Promise.resolve(false),
  supportedAuthenticationTypesAsync: () => Promise.resolve([]),
  authenticateAsync: () => Promise.resolve({ success: true }),
  notificationAsync: () => Promise.resolve(),
  impactAsync: () => Promise.resolve(),
  selectionAsync: () => Promise.resolve(),
};
